### ISSUE TITLE
View All Organizations

### ISSUE THREAD

**Issue by JFelz** [NSS-Evening-E22/HackDonations_Client#3]
Given: An authenticated User.
When: They choose to view all Donations.
Then: They should see a list of all Donations with relevant details.

**Comment by Bonni535** [comment]
ViewOrganizations component completed.

`
export default function ViewOrganizations() {
  const [organizationDetails, setOrganizationDetails] = useState({});
  const router = useRouter();
  const { firebaseKey } = router.query;

  useEffect(() => {
    getSingleOrganization(firebaseKey).then(setOrganizationDetails);
  }, [firebaseKey]);

  return (
    <div className="mt-5 d-flex flex-wrap">
      <div className="d-flex flex-column">
        <Image src={organizationDetails.imageUrl} alt={organizationDetails.title} style={{ width: '300px' }} />
      </div>
      Description:
      <p>{organizationDetails.description || ''}</p>
      <hr />
    </div>
  );
}
`
